(function(){
  async function loopGif(file){const source=new Uint8Array(await file.arrayBuffer()),sig=String.fromCharCode(...source.slice(0,6));if(sig!=='GIF87a'&&sig!=='GIF89a')return file;for(const name of ['NETSCAPE2.0','ANIMEXTS1.0']){const bytes=[...name].map(c=>c.charCodeAt(0));for(let start=0;start<=source.length-bytes.length;start++){if(!bytes.every((b,o)=>source[start+o]===b))continue;if(start+14<source.length&&source[start+11]===3&&source[start+12]===1){const p=source.slice();p[start+13]=0;p[start+14]=0;return new Blob([p],{type:'image/gif'})}}}const packed=source[10],table=packed&128?3*(2**((packed&7)+1)):0,at=13+table;if(at>source.length)return file;const ext=new Uint8Array([33,255,11,...[...'NETSCAPE2.0'].map(c=>c.charCodeAt(0)),3,1,0,0,0]),p=new Uint8Array(source.length+ext.length);p.set(source.slice(0,at));p.set(ext,at);p.set(source.slice(at),at+ext.length);return new Blob([p],{type:'image/gif'})}
  window.createSceneMedia=function(render,W,H){const state={url:null,aspect:1,scene:0},nodes={object:document.getElementById('objectMedia'),image:document.getElementById('imageMedia')},used=new Set(),input=document.getElementById('objectImageUpload'),remove=document.getElementById('removeObjectImage'),status=document.getElementById('uploadStatus'),picker=document.getElementById('builtInScenes'),allowed=new Set(['image/png','image/jpeg','image/webp','image/gif']);
    function mark(n){state.scene=n;picker.querySelectorAll('[data-scene]').forEach(b=>b.classList.toggle('active',+b.dataset.scene===n))}
    function display(blob,text,scene=0){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(blob),probe=new Image();probe.onload=()=>{if(state.url)URL.revokeObjectURL(state.url);state.url=url;state.aspect=probe.naturalWidth/probe.naturalHeight||1;nodes.object.src=url;nodes.image.src=url;status.textContent=text;remove.hidden=false;mark(scene);render();resolve()};probe.onerror=()=>{URL.revokeObjectURL(url);reject()};probe.src=url})}
    input.addEventListener('change',async()=>{const file=input.files&&input.files[0];if(!file)return;if(!allowed.has(file.type)){status.textContent='Please choose a PNG, JPG, WebP or GIF file.';input.value='';return}if(file.size>8*1024*1024){status.textContent='That file is larger than 8 MB.';input.value='';return}try{await display(file.type==='image/gif'?await loopGif(file):file,file.type==='image/gif'?`${file.name} · looping continuously · displayed locally`:`${file.name} · displayed locally`)}catch(e){status.textContent='This image could not be displayed.';input.value=''}});
    picker.addEventListener('click',async e=>{const b=e.target.closest('[data-scene]');if(!b)return;const n=+b.dataset.scene,buttons=[...picker.querySelectorAll('[data-scene]')];buttons.forEach(x=>x.disabled=true);status.textContent=`Loading scene ${n}…`;try{const response=await fetch(`assets/scenes/scene-${n}.gif`);if(!response.ok)throw Error();await display(await loopGif(await response.blob()),`Scene ${n} · looping continuously`,n);input.value=''}catch(err){status.textContent=`Scene ${n} could not be loaded.`}finally{buttons.forEach(x=>x.disabled=false)}});
    remove.addEventListener('click',()=>{if(state.url)URL.revokeObjectURL(state.url);state.url=null;state.aspect=1;nodes.object.removeAttribute('src');nodes.image.removeAttribute('src');input.value='';remove.hidden=true;mark(0);status.textContent='PNG, JPG, WebP or GIF · maximum 8 MB';render()});
    return{state,begin(){used.clear()},size(m=1){const h=72*Math.abs(m),a=Math.max(.25,Math.min(2.5,state.aspect));return{height:h,width:h*a}},place(kind,x,y,size,virtual=false,inverted=false){if(!state.url)return;const n=nodes[kind];used.add(kind);n.style.visibility='visible';n.style.left=`${x/W*100}%`;n.style.top=`${y/H*100}%`;n.style.width=`${size.width/W*100}%`;n.style.height=`${size.height/H*100}%`;n.style.transform=`translate(-50%,-50%)${inverted?' scaleY(-1)':''}`;n.classList.toggle('virtual-picture',virtual)},finish(){Object.entries(nodes).forEach(([k,n])=>{if(!used.has(k))n.style.visibility='hidden'})}};
  }
})();
